name: test

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['10', '12', '14', '16']

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Build
        run: npm install && npm run build

      - name: Test
        run: npm test
